jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gpuadmin/UM_CISC7404_Reinforcement_gym_game/parallel-sac.py", line 537, in <module>
    train_state = train(train_state, config, env_reset, env_step, env_params, buffer)
  File "/home/gpuadmin/UM_CISC7404_Reinforcement_gym_game/parallel-sac.py", line 375, in train
    obs, state = env_reset(reset_key, env_params)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/equinox/_jit.py", line 209, in __call__
    return _call(self, False, args, kwargs)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/equinox/_jit.py", line 263, in _call
    marker, _, _ = out = jit_wrapper._cached(
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/gymnax/environments/environment.py", line 62, in reset
    obs, state = self.reset_env(key, params)
  File "/home/gpuadmin/popgym_arcade/popgym_arcade/environments/skittles.py", line 248, in reset_env
    key, subkey1 = jax.random.split(key)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/jax/_src/random.py", line 290, in split
    typed_key, wrapped = _check_prng_key("split", key)
  File "/home/gpuadmin/miniconda3/envs/jax_rl/lib/python3.10/site-packages/jax/_src/random.py", line 99, in _check_prng_key
    raise ValueError(f"{name} accepts a single key, but was given a key array of"
ValueError: split accepts a single key, but was given a key array of shape (8, 2) != (). Use jax.vmap for batching.
